DELETE FROM users;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;

DELETE FROM categories;
ALTER TABLE categories ALTER COLUMN id RESTART WITH 1;

DELETE FROM locations;
ALTER TABLE locations ALTER COLUMN id RESTART WITH 1;

DELETE FROM events;
ALTER TABLE events ALTER COLUMN id RESTART WITH 1;

DELETE FROM compilations;
ALTER TABLE compilations ALTER COLUMN id RESTART WITH 1;

DELETE FROM requests;
ALTER TABLE requests ALTER COLUMN id RESTART WITH 1;

-- DROP TABLE IF EXISTS users CASCADE;
-- DROP TABLE IF EXISTS categories CASCADE;
-- DROP TABLE IF EXISTS locations CASCADE;
-- DROP TABLE IF EXISTS events CASCADE;
-- DROP TABLE IF EXISTS compilations CASCADE;
-- DROP TABLE IF EXISTS requests CASCADE;
-- DROP TABLE IF EXISTS compilations_events CASCADE;