version: '3.1'

services:

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-stats
      - POSTGRES_USER=vetal
      - POSTGRES_PASSWORD=9379992

  stats-server:
    build: stats/stats-server
    image: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=explore-stats
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=vetal
      - POSTGRES_PASSWORD=9379992


  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore-main
      - POSTGRES_USER=vetal
      - POSTGRES_PASSWORD=9379992

  ewm-service:
    build: main-service
    image: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - DB_NAME=explore-main
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=vetal
      - POSTGRES_PASSWORD=9379992